
[project]
name = "clarinet"

[clarigen]
output_dir = "tmp/clarion"
docs = "tmp/docs"

[contracts.simple]
path = "contracts/simple.clar"
depends_on = []

[contracts.ext]
path = "contracts/external/ext.clar"
depends_on = []