name: Compile
on:
  push:
    branches:
      - 'feat/v1'

jobs:
  compile_and_push:
    name: Compile and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16.9.1
          cache: 'yarn'
      - name: Install monorepo deps
        run: npx lerna bootstrap
      - name: Build packages
        run: yarn build
      - name: Move compiled Deno package
        run: |
          cp -R packages/core/dist deno
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Created deno folder"
      - name: Push to branch
        uses: ad-m/github-push-action@dda7a419b68b689726f81bf2f2930fe14ff821ef
        with:
          branch: compiled