name: Publish
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish_npm:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare repository
        run: git checkout main
      - name: Set Node Version
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.9.1
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install monorepo deps
        run: npx lerna bootstrap
      - name: Build packages
        run: yarn build
      - name: Type checks
        run: yarn typecheck
      - name: Tests
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Stash changes
        run: git stash
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@c3d88279fd9abe11410de073005e34863f735b1c
        with:
          publish: yarn publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}